vcpkg_download_distfile(ARCHIVE
    URLS "https://download.gnome.org/sources/pangomm/2.42/pangomm-2.42.2.tar.xz"
    FILENAME "pangomm-2.42.2.tar.xz"
    SHA512 5e4826d64c0178527b4df73e901d2fdf5661d41777e189f5e2d4b26577e42689efaccf5a28502246c6b3926571ccd5876cb23d33267b44ace7ee164322c14667
)

vcpkg_extract_source_archive(
    SOURCE_PATH
    ARCHIVE ${ARCHIVE}
)

# Patch to add missing pango-markup.h include
vcpkg_replace_string("${SOURCE_PATH}/pango/src/attrlist.ccg" 
    "// -*- c++ -*-"
    "// -*- c++ -*-\n#include <pango/pango-markup.h>")

vcpkg_configure_meson(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS
        -Dmsvc14x-parallel-installable=false
        -Dbuild-documentation=false
    ADDITIONAL_BINARIES
        glib-genmarshal='${CURRENT_HOST_INSTALLED_DIR}/tools/glib/glib-genmarshal'
        glib-mkenums='${CURRENT_HOST_INSTALLED_DIR}/tools/glib/glib-mkenums'
        glibmm_generate_extra_defs-2.4='${CURRENT_HOST_INSTALLED_DIR}/tools/glibmm/glibmm_generate_extra_defs-2.4'
)

# Patch generated files to add missing pango-markup.h include
# These are generated by gmmproc during configure and are not patched by the .ccg patch
file(GLOB_RECURSE attrlist_cc 
    "${SOURCE_PATH}/untracked/pango/pangomm/attrlist.cc")
foreach(file ${attrlist_cc})
    vcpkg_replace_string("${file}"
        "// Generated by gmmproc"
        "// Generated by gmmproc\n#include <pango/pango-markup.h>")
endforeach()

vcpkg_install_meson()
vcpkg_fixup_pkgconfig()
vcpkg_copy_pdbs()

vcpkg_install_copyright(FILE_LIST "${SOURCE_PATH}/COPYING")